# Generated by Django 5.1.2 on 2024-10-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_alter_cantidad_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='turno_entrada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='turno_salida',
            field=models.TimeField(),
        ),
    ]
