# Generated by Django 5.1.2 on 2024-10-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0004_alter_admin_contrasena_alter_admin_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidad',
            name='cantidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='turno_entrada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='turno_salida',
            field=models.TimeField(),
        ),
    ]
